### PR TITLE
Fix address validation issues

### LINKED ISSUE #475: Infinite loading when a address line with more than 35 characters was provided
```
PUT /v2/user/abff2cb4-0806-42b2-8804-9e813039b682 failed: 400, Street and house number may not be longer than 35 characters. 
```

- [x] Always show backend errors to the user instead of getting into an invalid state
- [x] Add form validation for address line (35 characters)
- [x] Add form validation for first and lass name (20 characters each)

### PR DESCRIPTION
**Pull request by dreampulse**
Fixes #475

# Definition of Done

- [x] The code does at least what is defined in the ticket and does not affect any other functionality
- [x] The PR has a meaningful title
- [x] There is a link to the issue-id
- [x] There are no 'hacks' or shortcuts refactoring is preferred
- [x] The happy case of the app was tested at least once manually

### CODE REVIEW

File: src/app/container/address-page.js [hunk 1]
```diff
@@ -32,6 +32,11 @@ const email = value =>
 const tel = value =>
   !value || (value && !/^[+]?[0-9\-\s()]*$/i.test(value)) ? 'Invalid phone number' : undefined
 
+const maxLength = max => value => (!value || value.length > max ? 'Field too long' : undefined)
```
Comment (webholics) [inline src/app/container/address-page.js]: you now mixed up the required validator with the maxLength validator.
If I leave the fields empty I'll get the error "Field too long" which is quite misleading.

It would have been better to union both validators:
```
maxLength30 = maxLength(30)
validateStreet = value => required(value) || maxLength30(value) || undefined
```

Comment (webholics) [reply src/app/container/address-page.js]: also shouldn't we use maxlength on the input field itself? would be much less trial and error for the user.
