### PR TITLE
Fix unexpected error during address input

### LINKED ISSUE #415: BUG: Unexpected error message during address input

### PR DESCRIPTION
**Pull request by jhnns**
Fixes #415

This PR reverts some of the changes that have been introduced with https://github.com/all3dp/printing-engine-client/commit/1a34ed8871d0d0d2c1e80a03eae83649787f778f: We take the `shipping.name` into account again to find the updated offer. Otherwise it just selects the first offer that has the same `materialConfigId` and `printingService`, neglecting the actual shipping method. This led to a situation where the shipping method was actually changed, based on the random order of the offer (thus the alert about the changed price, the price did actually change!)

Now if the updated offer is not available anymore, we just select the cheapest offer for this `materialConfigId` and for the given `printingService`.

# Definition of Done

- [ ] The code does at least what is defined in the ticket and does not affect any other functionality
- [ ] The PR has a meaningful title
- [ ] There is a link to the issue-id
- [ ] The PR has been reviewed
- [ ] There are no 'hacks' or shortcuts refactoring is prefered

## Tests
- [ ] Reasonably tested with high code coverage (unit/integration)

##	Testability
- [ ] All exported functions are testable
- [ ] There is no code execution in the global scope
- [ ] Default exports are avoided
- [ ] The code is concise, expressive and readable
- [ ] The code is functional and doesn’t use class syntax

## React components are
- [ ] Stateless and use pure rendering functions
- [ ] Are documented and tested in storybook
- [ ] Typed-checked
- [ ] The Sass is stickily using the BEM-Convention
- [ ] For each react component exists exactly one Sass-File
- [ ] The is no container styled
- [ ] There are no console errors or unwanted console logs

### CODE REVIEW

File: src/app/lib/offer.js [hunk 1]
```diff
@@ -1,6 +1,25 @@
...
-      offer.printingService === selectedOffer.printingService
+      offer.printingService === selectedOffer.printingService &&
+      offer.shipping.name === selectedOffer.shipping.name
   ) || null
+
+export const getCheapestOfferFor = (
+  materialConfigId: string,
+  printingService: string,
+  offers: Array<Offer>
+) => {
```
Comment (henry-all3dp) [inline src/app/lib/offer.js]: Is there a reason that another method signature is used in getCheapestOfferFor compared to getUpdatedOffer?

Comment (henry-all3dp) [reply src/app/lib/offer.js]: Used signature makes sense in this context. Therefore, no change needed 🙂
