### PR TITLE
Switch to order number and fix error handling for order-failed

### LINKED ISSUE #363: Render new `orderNumber` attribute instead of `orderId` on success page after creating an order
In order to fix https://github.com/all3dp/printing-engine/issues/212 order IDs are now UUIDs. I added a new `orderNumber` in the order creation response (see https://printing-engine.all3dp.com/docs). This attribute should be rendered instead of the `orderId` on success page after creating an order.

Here is the corresponding server PR https://github.com/all3dp/printing-engine/pull/343

### PR DESCRIPTION
**Pull request by dreampulse**
Fixes #363 

# Definition of Done

- [ ] The code does at least what is defined in the ticket and does not affect any other functionality
- [ ] The PR has a meaningful title
- [ ] There is a link to the issue-id
- [ ] The PR has been reviewed
- [ ] There are no 'hacks' or shortcuts refactoring is prefered

## Tests
- [ ] Reasonably tested with high code coverage (unit/integration)

##	Testability
- [ ] All exported functions are testable
- [ ] There is no code execution in the global scope
- [ ] Default exports are avoided
- [ ] The code is concise, expressive and readable
- [ ] The code is functional and doesn’t use class syntax

## React components are
- [ ] Stateless and use pure rendering functions
- [ ] Are documented and tested in storybook
- [ ] Typed-checked
- [ ] The Sass is stickily using the BEM-Convention
- [ ] For each react component exists exactly one Sass-File
- [ ] The is no container styled
- [ ] There are no console errors or unwanted console logs

### CODE REVIEW

File: src/app/container/success-page.js [hunk 1]
```diff
@@ -17,7 +17,9 @@ const CartPage = ({offer, order}) => {
     <Section modifiers={['highlight']}>
       <Headline
         label={
-          order.orderId ? `Order number: ${order.orderId}` : 'Thank you for ordering at ALL3DP!'
+          order.orderNumber
+            ? `Order number: ${order.orderNumber}`
```
Comment (jhnns) [inline src/app/container/success-page.js]: Da wird sie verwendet, jetzt seh ich es :)
